valptridx: fix ambiguous overload resolution
gcc-15 and clang-18 both reject the previous code.  gcc-12, gcc-13, and
gcc-14 accept the previous code.  gcc-14 produces the same program with
both the old and new code, so this is not a behavior change.

gcc-15 rejects the old code with:
```
In file included from similar/main/aipath.cpp:51:
similar/main/aipath.cpp: In function 'void d2x::{anonymous}::ai_path_garbage_collect()':
similar/main/aipath.cpp:1367:35: error: ambiguous overload for 'operator*' (operand type is 'valptridx<d2x::object>::basic_vval_member_factory<valptridx<d2x::object>::ptridx<valptridx<d2x::object>::vc>, valptridx<d2x::object>::ptridx<valptridx<d2x::object>::vm> >::iterator<valptridx<d2x::object>::ptridx<valptridx<d2x::object>::vc> >' {aka 'valptridx<d2x::object>::factory_range_iterator<valptridx<d2x::object>::ptridx<valptridx<d2x::object>::vc> >'})
 1367 |     range_for (const auto &&objp, vcobjptridx)
      |                                   ^~~~~~~~~~~
common/include/compiler-range_for.h:9:31: note: in definition of macro 'range_for'
    9 | #define range_for(A,B)  for(A:B)
      |                               ^
similar/main/aipath.cpp:1367:35: note: candidate: 'operator*(valptridx<d2x::object>::ptr<valptridx<d2x::object>::vc>::const_pointer_type {aka const d2x::object*})' (built-in)
 1367 |     range_for (const auto &&objp, vcobjptridx)
      |                                   ^~~~~~~~~~~
common/include/compiler-range_for.h:9:31: note: in definition of macro 'range_for'
    9 | #define range_for(A,B)  for(A:B)
      |                               ^
similar/main/aipath.cpp:1367:35: note: candidate: 'operator*(valptridx<d2x::object>::ptr<valptridx<d2x::object>::vc>::mutable_pointer_type {aka d2x::object*})' (built-in)
 1367 |     range_for (const auto &&objp, vcobjptridx)
      |                                   ^~~~~~~~~~~
common/include/compiler-range_for.h:9:31: note: in definition of macro 'range_for'
    9 | #define range_for(A,B)  for(A:B)
      |                               ^
In file included from common/main/object.h:40,
                 from similar/main/aipath.cpp:36:
common/include/valptridx.h:672:15: note: candidate: 'typename policy::reference valptridx<managed_type>::ptr<policy>::operator*() const & [with policy = valptridx<d2x::object>::vc; managed_type = d2x::object; typename policy::reference = const d2x::object&]'
  672 |     reference operator*() const &
      |               ^~~~~~~~
common/include/valptridx.h:1229:16: note: candidate: 'valptridx<managed_type>::factory_range_iterator<T>::value_type valptridx<managed_type>::factory_range_iterator<T>::operator*() const & requires !(is_same_v<typename std::conditional<requires{typename T::vidx_type;}, T, managed_type>::type, managed_type>) [with T = valptridx<d2x::object>::ptridx<valptridx<d2x::object>::vc>; managed_type = d2x::object; value_type = valptridx<d2x::object>::ptridx<valptridx<d2x::object>::vc>]'
 1229 |     value_type operator*() const &
      |                ^~~~~~~~
```

Reported-by: koo5 <https://github.com/dxx-rebirth/dxx-rebirth/issues/803> (clang-18 only)