Mark variadic forwarding constructor as `constexpr`
This is safely ignored when the constructor cannot satisfy `constexpr`.
Without this modifier, forwarding to `constexpr` constructors is not
`constexpr`, which causes build failures.

clang-5 with `sconf_cxx11_inherit_constructor=force-failure`:
```
    similar/main/gauges.cpp:553:61: error: constexpr constructor's 1st parameter type 'const (anonymous namespace)::hud_x_scale_float' (aka 'const hud_scale_float<'x'>') is not a literal type
    similar/main/gauges.cpp:432:7: note: 'hud_scale_float<'x'>' is not literal because it is not an aggregate and has no constexpr constructors other than copy or move constructors
```

Fixes: 893e8cde06f442b7b5f7f62a5c8dd5e40a26c983 ("Combine hud gauge parameters")