Avoid bogus gcc-14 -Warray-bounds warning in multi_sort_kill_list
gcc-14 warns for errors in its own standard library functions, even when
those errors are unreachable.  In this case, it computes `begin + 16`,
then warns that `+16` is beyond the end of the 8 element long array.
However, the invalid access is inside an `if` clause that is only true
for ranges of at least 16 elements, so the invalid access is
unreachable.

Add an explicit early exit for `N_players` too large, and switch to use
of `std::span`, which gcc-14 seems to be able to trace well enough to
prove that this path is unreachable.  This change avoids generating the
bogus -Warray-bounds warning.  This change removes the runtime exception
from `partial_range` when `N_players` is out of range, and instead
handles an invalid `N_players` by leaving the list unsorted.

```
In function 'constexpr void std::__final_insertion_sort(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = unsigned int*; _Compare = __gnu_cxx::__ops::_Iter_comp_iter<ranges::__detail::__make_comp_proj<std::ranges::greater, std::reference_wrapper<const d2x::multi_sort_kill_list()::<lambda(unsigned int)> > >(std::ranges::greater&, std::reference_wrapper<const d2x::multi_sort_kill_list()::<lambda(unsigned int)> >&)::<lambda(auto:63&&, auto:64&&)> >]',
    inlined from 'constexpr void std::__sort(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = unsigned int*; _Compare = __gnu_cxx::__ops::_Iter_comp_iter<ranges::__detail::__make_comp_proj<std::ranges::greater, std::reference_wrapper<const d2x::multi_sort_kill_list()::<lambda(unsigned int)> > >(std::ranges::greater&, std::reference_wrapper<const d2x::multi_sort_kill_list()::<lambda(unsigned int)> >&)::<lambda(auto:63&&, auto:64&&)> >]' at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/stl_algo.h:1908:31,
    inlined from 'constexpr void std::sort(_RAIter, _RAIter, _Compare) [with _RAIter = unsigned int*; _Compare = ranges::__detail::__make_comp_proj<std::ranges::greater, std::reference_wrapper<const d2x::multi_sort_kill_list()::<lambda(unsigned int)> > >(std::ranges::greater&, std::reference_wrapper<const d2x::multi_sort_kill_list()::<lambda(unsigned int)> >&)::<lambda(auto:63&&, auto:64&&)>]' at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/stl_algo.h:4804:18,
    inlined from 'constexpr _Iter std::ranges::__sort_fn::operator()(_Iter, _Sent, _Comp, _Proj) const [with _Iter = unsigned int*; _Sent = unsigned int*; _Comp = std::ranges::greater; _Proj = std::reference_wrapper<const d2x::multi_sort_kill_list()::<lambda(unsigned int)> >]' at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/ranges_algo.h:1783:22,
    inlined from 'constexpr std::ranges::borrowed_iterator_t<_Range> std::ranges::__sort_fn::operator()(_Range&&, _Comp, _Proj) const [with _Range = partial_range_t<unsigned int*, void>; _Comp = std::ranges::greater; _Proj = std::reference_wrapper<const d2x::multi_sort_kill_list()::<lambda(unsigned int)> >]' at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/ranges_algo.h:1794:16,
    inlined from 'void d2x::multi_sort_kill_list()' at similar/main/multi.cpp:845:19:
/usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/stl_algo.h:1817:28: error: array subscript 16 is outside array bounds of 'dcx::per_player_array<unsigned int> [1]' {aka 'std::array<unsigned int, 8> [1]'} [-Werror=array-bounds=]
 1817 |       std::__insertion_sort(__first, __first + int(_S_threshold), __comp);
```