Use no code optimisation for the Debugger build, so Xcode's debugger (others?) can debug properly.
After making this change to SConstruct Apple's linker complains of missing symbols:
Undefined symbols for architecture x86_64:
  "newmenu_item::imenu_specific_type::nm_type", referenced from:
      newmenu_item::input_or_menu() in .d1x-rebirth.newmenu.o
  "newmenu_item::input_specific_type::nm_type", referenced from:
      newmenu_item::input_or_menu() in .d1x-rebirth.newmenu.o
  "newmenu_item::number_specific_type::nm_type", referenced from:
      newmenu_item::number_or_slider() in .d1x-rebirth.newmenu.o
  "newmenu_item::slider_specific_type::nm_type", referenced from:
      newmenu_item::number_or_slider() in .d1x-rebirth.newmenu.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Therefore, using #define constants instead of integral constants so Clang (others?) doesn't get confused.